### ISSUE TITLE
missing parts

### ISSUE THREAD

**Issue by yeettheskees** [SteveBenz/ProgressiveColonizationSystem#10]
Hello I've been playing with this mod for a while and i'm liking it but I can't find the parts to make shinies and fertilizer. Checking out the parts folder I can see the config file for it but not the image file for it like i believe it should have. I downloaded it with ckan. I tried manually intalling it but the same happens.

**Comment by SteveBenz** [comment]
The part uses the same visual model as the ISRU converter, so it doesn't have its own model and texture files.  Look for it in the PKS tab in the Vehicle Assembly Building.  You also might not have unlocked it yet, it's pretty far down the tech tree.

**Comment by yeettheskees** [comment]
I found the problem. Even in sandbox mode they didn't show up. So I tried uninstalling restock and verifying game files and now the parts show up :)

**Comment by FoxxenD** [comment]
Hi, on the KSP forum thread of the mod, someone shared something for Restock users to avoid this problem : [https://forum.kerbalspaceprogram.com/index.php?/topic/181852-15x~17x-progressivecolonizationsystem-life-support-colonization-for-more-fun-in-late-game/&do=findComment&comment=4170486](https://forum.kerbalspaceprogram.com/index.php?/topic/181852-15x~17x-progressivecolonizationsystem-life-support-colonization-for-more-fun-in-late-game/&do=findComment&comment=4170486) (a workaround I suppose)

**Comment by SteveBenz** [comment]
Fixed by #11

**Comment by lingfors** [comment]
Hi, this is (as you probably already know) fixed in HEAD but still broken in the latest release. I was able to fix it by getting the whitelist from here, but for the sanity of other people that might not know how to do this may I suggest you release an official bug fix release?

Thanks.
