### ISSUE TITLE
EligibleToSkipTier1

### ISSUE THREAD

**Issue by richardemaine** [SteveBenz/ProgressiveColonizationSystem#8]
Copied from my forum posting as you said you check github more often (though I don't see barely any other issues posted here).

A problem I've occasionally seen before, but this time I captured a log file. The PKS window occasionally disappears when I try to open the progress window. Seems like it has always been when there isn't yet any progress made yet and also none being made. I initially thought something like a 0/0 in calculating the percentage done, but in the log file I see what looks like an infinite loop of exceptions referring to get_TierBeingResearched and EligibleToSkipTier1. I'm guessing that's the data you need, but I'll link the log files just in case. This is my first base in this particular playthrough and it is right after I added the first rocket parts factory, which doesn't yet have enough mechanics to run it (one is about to walk over from a nearby ship). To make these logs, I started the game, used the stock alarm clock to switch to the base in question (mun base 0) as I had available a recent alarm for finishing construction of the rocket parts factory, clicked on the cupcake icon, and then clicked on the progress tab.

https://www.dropbox.com/s/n6ongxpba1phbtg/Player.log?dl=0

https://www.dropbox.com/s/b7qks45qykoh4lp/KSP.log?dl=0

Easy enough to work around, as the problem goes away once I start making some actual progress to report in the tab.

**Comment by SteveBenz** [comment]
Fixed it in v3.1.3 - sorry for not noticing this post earlier!
